# Generated by Django 6.1 on 2026-08-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='faces/')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
